/**
 * Renders lib/seed-data/* into the seed migrations:
 *   supabase/migrations/002_seed_onboarding.sql
 *   supabase/migrations/003_assessments.sql
 *
 *   npx tsx scripts/generate-seed-sql.ts
 *
 * Re-run after editing the default programme content. Production edits
 * are made in the app (Programme Configuration), not here.
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { TEMPLATE, DAYS, GATES, TASKS, SEGMENTS, SETTINGS } from "../lib/seed-data/journey";
import { ASSESSMENTS, QUESTIONS, SCENARIOS } from "../lib/seed-data/assessments";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number") return String(v);
  if (typeof v === "boolean") return v ? "true" : "false";
  return `'${String(v).replace(/'/g, "''")}'`;
};
const arr = (xs: string[]) => (xs.length ? `array[${xs.map(q).join(",")}]::text[]` : "'{}'::text[]");
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const gateFor = (day: number) => SEGMENTS.find((s) => day >= s.from && day <= s.to)!.gate;

const root = path.resolve(__dirname, "..", "supabase", "migrations");
const header = (title: string) =>
  `-- ════════════════════════════════════════════════════════════════════\n-- ${title}\n-- GENERATED by scripts/generate-seed-sql.ts from lib/seed-data — edit the source, then regenerate.\n-- ════════════════════════════════════════════════════════════════════\n\n`;

// ── 002 ─────────────────────────────────────────────────────────────
let s = header("FirstGear KAM Onboarding Compass — 002 seed onboarding programme");
s += `insert into public.roles (id, name, description) values
  ('KAM','Key Account Manager','New or reassigned KAM in onboarding'),
  ('MENTOR','Mentor','Prior KAM / SME who coaches and reviews'),
  ('REPORTING_BOSS','Reporting Boss','KAM Head — final decision-maker for independent account handling'),
  ('HR_ADMIN','HR / Admin','Programme owner and administrator')
on conflict (id) do nothing;\n\n`;

s += `insert into public.app_settings (key, value, category, label, description, value_type) values\n`;
s += SETTINGS.map((x) => `  (${q(x.key)}, ${json(x.value)}, ${q(x.category)}, ${q(x.label)}, ${q(x.description)}, ${q(x.type)})`).join(",\n");
s += `\non conflict (key) do nothing;\n\n`;

s += `insert into public.onboarding_templates (code, name, description, duration_days)
values (${q(TEMPLATE.code)}, ${q(TEMPLATE.name)}, ${q(TEMPLATE.description)}, ${TEMPLATE.duration})
on conflict (code) do nothing;\n\n`;

s += `with tpl as (select id from public.onboarding_templates where code = ${q(TEMPLATE.code)})
insert into public.onboarding_days (template_id, day_number, phase, segment, title, pillars, objectives, resources, gate_code)
select tpl.id, d.* from tpl, (values\n`;
s += DAYS.map((d) => `  (${d.day}, ${d.phase}, ${q(d.segment)}, ${q(d.title)}, ${arr(d.pillars)}, ${arr(d.objectives)}, ${json(d.resources)}, ${q(d.gate ?? null)})`).join(",\n");
s += `\n) as d(day_number, phase, segment, title, pillars, objectives, resources, gate_code)
on conflict (template_id, day_number) do nothing;\n\n`;

s += `with tpl as (select id from public.onboarding_templates where code = ${q(TEMPLATE.code)})
insert into public.gate_definitions (template_id, code, day_number, name, description, gate_type, approver_role, unlocks, sort_order)
select tpl.id, g.* from tpl, (values\n`;
s += GATES.map((g, i) => `  (${q(g.code)}, ${g.day}, ${q(g.name)}, ${q(g.description)}, ${q(g.type)}, ${q(g.approver)}, ${arr(g.unlocks)}, ${i + 1})`).join(",\n");
s += `\n) as g(code, day_number, name, description, gate_type, approver_role, unlocks, sort_order)
on conflict (template_id, code) do nothing;\n\n`;

s += `with tpl as (select id from public.onboarding_templates where code = ${q(TEMPLATE.code)})
insert into public.tasks (template_id, code, day_number, title, description, pillar, task_type, owner_role, due_day,
                          is_mandatory, requires_approval, exposure, gate_code, action_ref, knowledge_topic, sort_order)
select tpl.id, t.* from tpl, (values\n`;
s += TASKS.map((t, i) =>
  `  (${q(t.code)}, ${t.day}, ${q(t.title)}, ${q(t.description)}, ${q(t.pillar)}, ${q(t.type)}, ${q(t.owner ?? "KAM")}, ${t.due ?? t.day}, ${q(t.mandatory ?? true)}, ${q(t.approval ?? false)}, ${q(t.exposure ?? "NONE")}, ${q(gateFor(t.day))}, ${q(t.ref ?? null)}, ${q(t.topic ?? null)}, ${i + 1})`,
).join(",\n");
s += `\n) as t(code, day_number, title, description, pillar, task_type, owner_role, due_day,
          is_mandatory, requires_approval, exposure, gate_code, action_ref, knowledge_topic, sort_order)
on conflict do nothing;\n\n`;

const deps = TASKS.flatMap((t) => (t.dependsOn ?? []).map((d) => [t.code, d] as const));
s += `insert into public.task_dependencies (task_id, depends_on_task_id)
select t.id, d.id
from (values\n${deps.map(([a, b]) => `  (${q(a)}, ${q(b)})`).join(",\n")}
) as x(task_code, dep_code)
join public.onboarding_templates tpl on tpl.code = ${q(TEMPLATE.code)}
join public.tasks t on t.template_id = tpl.id and t.code = x.task_code
join public.tasks d on d.template_id = tpl.id and d.code = x.dep_code
on conflict do nothing;\n`;

writeFileSync(path.join(root, "002_seed_onboarding.sql"), s);

// ── 003 ─────────────────────────────────────────────────────────────
let a = header("FirstGear KAM Onboarding Compass — 003 assessment bank & scenario library");
a += `insert into public.assessments (code, title, description, stage, gate_code, available_from_day, time_limit_minutes) values\n`;
a += ASSESSMENTS.map((x) => `  (${q(x.code)}, ${q(x.title)}, ${q(x.description)}, ${q(x.stage)}, ${q(x.gate)}, ${x.from}, ${q(x.minutes)})`).join(",\n");
a += `\non conflict (code) do nothing;\n\n`;

a += `insert into public.assessment_questions (question_code, assessment_stage, question_type, pillar, topic, difficulty, question,
  options, correct_answer, explanation, weight, source_document, source_reference, sort_order) values\n`;
a += QUESTIONS.map((x, i) =>
  `  (${q(x.code)}, ${q(x.stage)}, ${q(x.type)}, ${q(x.pillar)}, ${q(x.topic)}, ${q(x.difficulty)}, ${q(x.question)},\n   ${json(x.options ?? [])}, ${json(x.correct)}, ${q(x.explanation)}, ${x.weight ?? 1}, ${q(x.source)}, ${q(x.ref)}, ${i + 1})`,
).join(",\n");
a += `\non conflict (question_code) do nothing;\n\n`;

a += `insert into public.scenario_templates (code, title, category, pillar, situation, prompt, rubric, red_flags,
  is_certification, requires_review, source_document, sort_order) values\n`;
a += SCENARIOS.map((x, i) =>
  `  (${q(x.code)}, ${q(x.title)}, ${q(x.category)}, ${q(x.pillar)}, ${q(x.situation)}, ${q(x.prompt)},\n   ${json(x.rubric)}, ${json(x.red_flags)}, ${q(x.certification)}, ${q(x.certification)}, ${q(x.source)}, ${i + 1})`,
).join(",\n");
a += `\non conflict (code) do nothing;\n`;

writeFileSync(path.join(root, "003_assessments.sql"), a);

console.log(`002: ${DAYS.length} days, ${GATES.length} gates, ${TASKS.length} tasks, ${deps.length} dependencies, ${SETTINGS.length} settings`);
console.log(`003: ${ASSESSMENTS.length} assessments, ${QUESTIONS.length} questions, ${SCENARIOS.length} scenarios`);
