-- ════════════════════════════════════════════════════════════════════
-- FirstGear KAM Onboarding Compass — 002 seed onboarding programme
-- GENERATED by scripts/generate-seed-sql.ts from lib/seed-data — edit the source, then regenerate.
-- ════════════════════════════════════════════════════════════════════

insert into public.roles (id, name, description) values
  ('KAM','Key Account Manager','New or reassigned KAM in onboarding'),
  ('MENTOR','Mentor','Prior KAM / SME who coaches and reviews'),
  ('REPORTING_BOSS','Reporting Boss','KAM Head — final decision-maker for independent account handling'),
  ('HR_ADMIN','HR / Admin','Programme owner and administrator')
on conflict (id) do nothing;

insert into public.app_settings (key, value, category, label, description, value_type) values
  ('PROGRAMME_NAME', '"FirstGear KAM Onboarding Compass"'::jsonb, 'programme', 'Programme name', 'Displayed across the application.', 'string'),
  ('PROGRAMME_DURATION', '30'::jsonb, 'programme', 'Programme duration (days)', 'Length of the standard journey before any extension.', 'number'),
  ('ONBOARDING_START_OFFSET_DAYS', '0'::jsonb, 'programme', 'Onboarding start day (offset from joining)', 'Days after the joining date that Day 1 begins for new instances.', 'number'),
  ('DAY_COUNTING', '"CALENDAR"'::jsonb, 'programme', 'Day counting', 'CALENDAR or BUSINESS days for due/overdue calculation.', 'string'),
  ('GOVERNANCE_WEIGHT', '25'::jsonb, 'scoring', 'Governance weight (%)', 'Day-15 pillar weight. Pillar weights must total 100.', 'number'),
  ('PEOPLE_WEIGHT', '20'::jsonb, 'scoring', 'People weight (%)', 'Day-15 pillar weight.', 'number'),
  ('PROCESS_WEIGHT', '30'::jsonb, 'scoring', 'Process weight (%)', 'Day-15 pillar weight.', 'number'),
  ('PRODUCT_WEIGHT', '25'::jsonb, 'scoring', 'Product weight (%)', 'Day-15 pillar weight.', 'number'),
  ('DAY15_GREEN_THRESHOLD', '80'::jsonb, 'gates', 'Day-15 Green threshold (%)', 'Score at or above this is Green.', 'number'),
  ('DAY15_AMBER_THRESHOLD', '60'::jsonb, 'gates', 'Day-15 Amber threshold (%)', 'Score at or above this (and below Green) is Amber; below is Red.', 'number'),
  ('DAY10_PASS_THRESHOLD', '70'::jsonb, 'gates', 'Day-10 knowledge check pass (%)', 'Minimum interim knowledge-check score to pass Gate 2.', 'number'),
  ('DAY21_PASS_THRESHOLD', '75'::jsonb, 'gates', 'Day-21 certification pass (%)', 'Minimum average certification score. Mentors cannot approve below this.', 'number'),
  ('DAY21_REQUIRED', 'true'::jsonb, 'gates', 'Day-21 certification required', 'Gate 4 must pass before pricing or customer ownership.', 'boolean'),
  ('PRICING_GATE_REQUIRED', 'true'::jsonb, 'gates', 'Pricing gate required', 'Pricing exposure needs a Green Day-15 score and Reporting Boss approval.', 'boolean'),
  ('CUSTOMER_OWNERSHIP_GATE_REQUIRED', 'true'::jsonb, 'gates', 'Customer-ownership gate required', 'Guided customer ownership needs Reporting Boss approval.', 'boolean'),
  ('AMBER_REFRESH_DAYS', '4'::jsonb, 'remediation', 'Amber refresh length (days)', 'Targeted refresh length for Amber (3–5).', 'number'),
  ('RED_EXTENSION_DAYS', '10'::jsonb, 'remediation', 'Red extension (days)', 'Proposed onboarding extension for Red.', 'number'),
  ('READINESS_WEIGHTS', '{"tasks":30,"knowledge":30,"scenario":25,"gates":15}'::jsonb, 'scoring', 'Overall readiness composition (%)', 'How the dashboard ''overall readiness'' combines task completion, knowledge score, scenario score and gate progress. Must total 100.', 'json'),
  ('REMINDER_LEAD_DAYS', '1'::jsonb, 'notifications', 'Reminder lead time (days)', 'How far ahead sessions, assessments and gates are flagged.', 'number'),
  ('SESSION_TYPES', '["HR Orientation","Mentor Check-in","Product Training","Process Training","Plant Walk","Customer 360 Review","Manager Review","Assessment","Scenario Certification","Readiness Panel"]'::jsonb, 'sessions', 'Session types', 'Session types available when scheduling.', 'json'),
  ('KNOWLEDGE_CATEGORIES', '["Company","Products","Customers","Sales","Processes","Training","Policies","Quality","Governance","Account"]'::jsonb, 'knowledge', 'Knowledge categories', 'Categories available for knowledge documents.', 'json'),
  ('RAG_TOP_K', '6'::jsonb, 'knowledge', 'Retrieved passages per answer', 'Number of passages passed to the generator.', 'number'),
  ('RAG_MIN_SIMILARITY', '0.35'::jsonb, 'knowledge', 'Minimum retrieval similarity', 'Below this, the assistant says evidence is insufficient instead of answering.', 'number')
on conflict (key) do nothing;

insert into public.onboarding_templates (code, name, description, duration_days)
values ('KAM-30', 'KAM 30-Day Readiness Journey', 'Guided, evidence-based onboarding for new or reassigned Key Account Managers. Days 1–15 learn the company; Days 16–30 guided ownership controlled by readiness gates.', 30)
on conflict (code) do nothing;

with tpl as (select id from public.onboarding_templates where code = 'KAM-30')
insert into public.onboarding_days (template_id, day_number, phase, segment, title, pillars, objectives, resources, gate_code)
select tpl.id, d.* from tpl, (values
  (1, 1, 'Learn the company', 'Governance & people', array['GOVERNANCE','PEOPLE']::text[], array['Understand the business, values and code of conduct','Complete HR orientation and onboarding setup','Understand the KAM charter and manager expectations']::text[], '[{"label":"Company overview","document_key":"COMPANY-OVERVIEW"},{"label":"Code of conduct","document_key":"CODE-OF-CONDUCT"},{"label":"KAM charter","document_key":"KAM-CHARTER"}]'::jsonb, null),
  (2, 1, 'Learn the company', 'Products', array['PRODUCT']::text[], array['Explain ICE, hybrid and BEV technology families','Map products to vehicle segments and applications']::text[], '[{"label":"Product portfolio guide","document_key":"PRODUCT-PORTFOLIO"}]'::jsonb, null),
  (3, 1, 'Learn the company', 'Processes & plant', array['PROCESS']::text[], array['Walk the plant and follow the manufacturing flow','Understand critical operations, traceability and logistics','Adopt the safety and quality mindset']::text[], '[{"label":"Manufacturing process overview","document_key":"MFG-PROCESS"}]'::jsonb, null),
  (4, 1, 'Learn the company', 'Governance & quality', array['GOVERNANCE','PROCESS']::text[], array['Understand customer-specific quality expectations','Explain APQP and PPAP at overview level','Know complaint handling and engineering change control']::text[], '[{"label":"Quality governance manual","document_key":"QUALITY-GOVERNANCE"}]'::jsonb, null),
  (5, 1, 'Learn the company', 'Organisational navigation', array['PEOPLE']::text[], array['Know who owns what across Engineering, NPD, Quality, SCM, Plant and Finance','Know where approved knowledge lives']::text[], '[{"label":"Ownership map & knowledge sources","document_key":"ORG-NAVIGATION"}]'::jsonb, 'G1'),
  (6, 1, 'Learn the company', 'KAM charter', array['GOVERNANCE']::text[], array['Understand the account ownership model','Know the governance calendar, KPIs, approval authority and escalation map']::text[], '[{"label":"KAM charter","document_key":"KAM-CHARTER"},{"label":"Approval authority matrix","document_key":"APPROVAL-MATRIX"}]'::jsonb, null),
  (7, 1, 'Learn the company', 'RFQ → quotation', array['PROCESS']::text[], array['Follow an RFQ from intake to approved quotation','Know the cross-functional inputs and approval chain']::text[], '[{"label":"RFQ to quotation SOP","document_key":"RFQ-SOP"}]'::jsonb, null),
  (8, 1, 'Learn the company', 'Costing & commercials (knowledge only)', array['PROCESS']::text[], array['Explain cost build-up, tooling and margin logic','Understand price-change and payment-term mechanics','Prepare for negotiation — no live pricing decisions']::text[], '[{"label":"Costing & commercial mechanics","document_key":"COSTING-COMMERCIALS"}]'::jsonb, null),
  (9, 1, 'Learn the company', 'Programme governance', array['GOVERNANCE']::text[], array['Understand nomination-to-SOP governance','Know APQP/PPAP touchpoints, engineering changes and the 8D interface']::text[], '[{"label":"Programme governance guide","document_key":"PROGRAMME-GOVERNANCE"},{"label":"Quality governance manual","document_key":"QUALITY-GOVERNANCE"}]'::jsonb, null),
  (10, 1, 'Learn the company', 'Practice & check', array['PROCESS','GOVERNANCE']::text[], array['Run a mock RFQ and a pricing scenario','Walk through a customer escalation','Pass the interim knowledge check']::text[], '[{"label":"RFQ to quotation SOP","document_key":"RFQ-SOP"},{"label":"Escalation playbook","document_key":"ESCALATION-PLAYBOOK"}]'::jsonb, 'G2'),
  (11, 1, 'Customer & business context', 'Customer 360 — organisation & strategy', array['PEOPLE','PRODUCT']::text[], array['Map the OEM organisation and strategic context','Document supplied parts and applications']::text[], '[{"label":"Customer 360 — Northwind Motors","document_key":"C360-NORTHWIND"}]'::jsonb, null),
  (12, 1, 'Customer & business context', 'Customer 360 — programmes & pipeline', array['PRODUCT','PROCESS']::text[], array['Document programmes, volumes and pipeline']::text[], '[{"label":"Customer 360 — Northwind Motors","document_key":"C360-NORTHWIND"}]'::jsonb, null),
  (13, 1, 'Stakeholders & history', 'Stakeholder map', array['PEOPLE']::text[], array['Identify purchasing, engineering, quality and SCM/plant contacts']::text[], '[{"label":"Customer 360 — Northwind Motors","document_key":"C360-NORTHWIND"}]'::jsonb, null),
  (14, 1, 'Stakeholders & history', 'Commercial history & lessons', array['GOVERNANCE','PROCESS']::text[], array['Understand pricing and commercial history','Record past commitments and lessons learned','Submit the account brief']::text[], '[{"label":"Customer 360 — Northwind Motors","document_key":"C360-NORTHWIND"}]'::jsonb, null),
  (15, 1, 'Readiness assessment', 'Day-15 readiness assessment', array['GOVERNANCE','PEOPLE','PROCESS','PRODUCT']::text[], array['Complete the four-pillar assessment','Customer 360 and account brief reviewed by Mentor','Readiness band decides Phase-2 access']::text[], '[{"label":"Assessment guide","document_key":"ASSESSMENT-GUIDE"}]'::jsonb, 'G3'),
  (16, 2, 'Shadow & prepare', 'Shadow customer & internal reviews', array['PEOPLE','PROCESS']::text[], array['Observe reviews and prepare minutes and action trackers']::text[], '[{"label":"Escalation playbook","document_key":"ESCALATION-PLAYBOOK"}]'::jsonb, null),
  (17, 2, 'Shadow & prepare', 'Draft (unsent) customer responses', array['PROCESS']::text[], array['Draft responses for mentor review — nothing is sent']::text[], '[]'::jsonb, null),
  (18, 2, 'Own low-risk actions', 'Routine customer queries', array['PROCESS','PEOPLE']::text[], array['Handle selected routine queries with mandatory pre-send review']::text[], '[]'::jsonb, null),
  (19, 2, 'Own low-risk actions', 'Coordinate cross-functional closure', array['PEOPLE']::text[], array['Drive closure across Quality, SCM, Plant and Engineering']::text[], '[]'::jsonb, null),
  (20, 2, 'Lead internal review', 'Lead account-action review', array['GOVERNANCE','PROCESS']::text[], array['Lead one review covering quality, delivery, commercial and programme topics — Mentor observes']::text[], '[]'::jsonb, null),
  (21, 2, 'Scenario certification', 'Scenario certification', array['PROCESS','GOVERNANCE']::text[], array['RFQ response, price challenge, delivery risk, quality escalation','Score against Day-15 baseline']::text[], '[{"label":"Escalation playbook","document_key":"ESCALATION-PLAYBOOK"},{"label":"RFQ to quotation SOP","document_key":"RFQ-SOP"}]'::jsonb, 'G4'),
  (22, 2, 'Guided pricing exposure', 'Prepare pricing position', array['PROCESS']::text[], array['Prepare a commercial position for joint discussion']::text[], '[{"label":"Costing & commercial mechanics","document_key":"COSTING-COMMERCIALS"},{"label":"Approval authority matrix","document_key":"APPROVAL-MATRIX"}]'::jsonb, null),
  (23, 2, 'Guided pricing exposure', 'Reporting Boss reviews position', array['GOVERNANCE']::text[], array['Reporting Boss reviews and challenges the position']::text[], '[]'::jsonb, null),
  (24, 2, 'Guided pricing exposure', 'Joint commercial discussion', array['PROCESS','PEOPLE']::text[], array['Join a live commercial discussion with the Reporting Boss']::text[], '[]'::jsonb, null),
  (25, 2, 'Guided pricing exposure', 'Draft negotiated position', array['PROCESS']::text[], array['Draft the follow-up position for Reporting Boss approval']::text[], '[]'::jsonb, null),
  (26, 2, 'Guided customer ownership', 'Own agreed account scope', array['PEOPLE','PROCESS']::text[], array['Own the agreed scope with daily light-touch review']::text[], '[]'::jsonb, null),
  (27, 2, 'Guided customer ownership', 'Ownership — daily review', array['PROCESS']::text[], array['Continue ownership; daily review']::text[], '[]'::jsonb, null),
  (28, 2, 'Guided customer ownership', 'Ownership — alternate-day review', array['PROCESS']::text[], array['Review cadence moves to alternate days']::text[], '[]'::jsonb, null),
  (29, 2, 'Guided customer ownership', 'Prepare panel evidence', array['GOVERNANCE']::text[], array['Assemble evidence of live-case performance and outputs']::text[], '[]'::jsonb, null),
  (30, 2, 'Readiness panel', 'Readiness panel & sign-off', array['GOVERNANCE','PEOPLE','PROCESS','PRODUCT']::text[], array['Panel evaluates knowledge, response quality, dependency reduction, live cases, scenarios and account understanding','Reporting Boss records the final human decision']::text[], '[]'::jsonb, 'G5')
) as d(day_number, phase, segment, title, pillars, objectives, resources, gate_code)
on conflict (template_id, day_number) do nothing;

with tpl as (select id from public.onboarding_templates where code = 'KAM-30')
insert into public.gate_definitions (template_id, code, day_number, name, description, gate_type, approver_role, unlocks, sort_order)
select tpl.id, g.* from tpl, (values
  ('G1', 5, 'Organisational readiness', 'Basic onboarding complete: governance, products, plant, quality and organisational navigation.', 'TASKS', null, array['SEGMENT_6_10']::text[], 1),
  ('G2', 10, 'Knowledge & practice checkpoint', 'Charter, RFQ-to-quotation and costing knowledge, mock RFQ and interim knowledge check.', 'ASSESSMENT', null, array['SEGMENT_11_15']::text[], 2),
  ('G3', 15, 'Four-pillar readiness assessment', 'Weighted Governance/People/Process/Product assessment with Customer 360 and account-brief review by the Mentor.', 'ASSESSMENT', 'MENTOR', array['PHASE_2']::text[], 3),
  ('G4', 21, 'Scenario certification', 'RFQ response, price challenge, delivery risk and quality escalation scenarios scored against the Day-15 baseline and reviewed by the Mentor.', 'SCENARIO', 'MENTOR', array['PRICING_ELIGIBLE','CUSTOMER_ELIGIBLE']::text[], 4),
  ('G5', 30, 'Readiness panel & sign-off', 'Reporting Boss, Mentor and HR panel. The Reporting Boss records the final, human-certified readiness decision.', 'PANEL', 'REPORTING_BOSS', array['INDEPENDENT_HANDLING']::text[], 5)
) as g(code, day_number, name, description, gate_type, approver_role, unlocks, sort_order)
on conflict (template_id, code) do nothing;

with tpl as (select id from public.onboarding_templates where code = 'KAM-30')
insert into public.tasks (template_id, code, day_number, title, description, pillar, task_type, owner_role, due_day,
                          is_mandatory, requires_approval, exposure, gate_code, action_ref, knowledge_topic, sort_order)
select tpl.id, t.* from tpl, (values
  ('D01-01', 1, 'Business overview', 'Read the company overview: businesses, plants, customers and strategy.', 'GOVERNANCE', 'LEARNING', 'KAM', 1, true, false, 'NONE', 'G1', null, 'company', 1),
  ('D01-02', 1, 'Company values', 'Review the company values and how they show up in customer work.', 'PEOPLE', 'LEARNING', 'KAM', 1, true, false, 'NONE', 'G1', null, 'values', 2),
  ('D01-03', 1, 'Code of conduct', 'Read and acknowledge the code of conduct, including gifts, hospitality and confidentiality.', 'GOVERNANCE', 'LEARNING', 'KAM', 1, true, false, 'NONE', 'G1', null, 'conduct', 3),
  ('D01-04', 1, 'HR orientation', 'Attend HR orientation: policies, leave, benefits and ways of working.', 'PEOPLE', 'SESSION', 'KAM', 1, true, false, 'NONE', 'G1', null, null, 4),
  ('D01-05', 1, 'KAM charter introduction', 'Read the KAM charter introduction: purpose, scope and accountability.', 'GOVERNANCE', 'LEARNING', 'KAM', 1, true, false, 'NONE', 'G1', null, 'charter', 5),
  ('D01-06', 1, 'Manager expectations', 'Meet the Reporting Boss to agree expectations for the first 30 days.', 'PEOPLE', 'SESSION', 'KAM', 1, true, false, 'NONE', 'G1', null, null, 6),
  ('D01-07', 1, 'Initial onboarding setup', 'Confirm your onboarding profile, mentor and session calendar in the Compass. (IT access is handled separately by IT.)', 'PEOPLE', 'ACTIVITY', 'KAM', 1, true, false, 'NONE', 'G1', null, null, 7),
  ('D02-01', 2, 'ICE technology families', 'Study the ICE product families and their key functions.', 'PRODUCT', 'LEARNING', 'KAM', 2, true, false, 'NONE', 'G1', null, 'ICE', 8),
  ('D02-02', 2, 'Hybrid technology families', 'Study hybrid product families and where they differ from ICE.', 'PRODUCT', 'LEARNING', 'KAM', 2, true, false, 'NONE', 'G1', null, 'hybrid', 9),
  ('D02-03', 2, 'BEV technology families', 'Study BEV product families: e-axle, thermal and battery-adjacent components.', 'PRODUCT', 'LEARNING', 'KAM', 2, true, false, 'NONE', 'G1', null, 'BEV', 10),
  ('D02-04', 2, 'Vehicle segments', 'Map products to passenger car, SUV, LCV and two-wheeler segments.', 'PRODUCT', 'LEARNING', 'KAM', 2, true, false, 'NONE', 'G1', null, 'segments', 11),
  ('D02-05', 2, 'Major manufacturing applications', 'Understand the major applications and the customer problems they solve.', 'PRODUCT', 'LEARNING', 'KAM', 2, true, false, 'NONE', 'G1', null, 'applications', 12),
  ('D03-01', 3, 'Plant walk', 'Walk the plant with the plant lead and follow one part from raw material to dispatch.', 'PROCESS', 'SESSION', 'KAM', 3, true, false, 'NONE', 'G1', null, null, 13),
  ('D03-02', 3, 'Manufacturing process flow', 'Learn the end-to-end manufacturing flow.', 'PROCESS', 'LEARNING', 'KAM', 3, true, false, 'NONE', 'G1', null, 'process flow', 14),
  ('D03-03', 3, 'Critical operations', 'Identify the critical operations and special characteristics.', 'PROCESS', 'LEARNING', 'KAM', 3, true, false, 'NONE', 'G1', null, 'critical operations', 15),
  ('D03-04', 3, 'Traceability', 'Understand lot traceability and how it supports containment.', 'PROCESS', 'LEARNING', 'KAM', 3, true, false, 'NONE', 'G1', null, 'traceability', 16),
  ('D03-05', 3, 'Logistics', 'Understand inbound and outbound logistics, packaging and schedules.', 'PROCESS', 'LEARNING', 'KAM', 3, true, false, 'NONE', 'G1', null, 'logistics', 17),
  ('D03-06', 3, 'Safety mindset', 'Complete the safety induction and understand plant safety rules.', 'PROCESS', 'LEARNING', 'KAM', 3, true, false, 'NONE', 'G1', null, null, 18),
  ('D03-07', 3, 'Quality mindset', 'Understand the zero-defect mindset and the cost of poor quality.', 'PROCESS', 'LEARNING', 'KAM', 3, true, false, 'NONE', 'G1', null, null, 19),
  ('D04-01', 4, 'Customer-specific quality mindset', 'Study customer-specific requirements (CSRs) for key OEMs.', 'GOVERNANCE', 'LEARNING', 'KAM', 4, true, false, 'NONE', 'G1', null, 'CSR', 20),
  ('D04-02', 4, 'APQP overview', 'Learn the five APQP phases and the KAM''s touchpoints.', 'PROCESS', 'LEARNING', 'KAM', 4, true, false, 'NONE', 'G1', null, 'APQP', 21),
  ('D04-03', 4, 'PPAP overview', 'Learn PPAP submission levels and elements.', 'PROCESS', 'LEARNING', 'KAM', 4, true, false, 'NONE', 'G1', null, 'PPAP', 22),
  ('D04-04', 4, 'Complaint handling', 'Understand the complaint-handling process and response timelines.', 'GOVERNANCE', 'LEARNING', 'KAM', 4, true, false, 'NONE', 'G1', null, 'complaints', 23),
  ('D04-05', 4, 'Engineering change-control governance', 'Understand how engineering changes are requested, approved and communicated.', 'GOVERNANCE', 'LEARNING', 'KAM', 4, true, false, 'NONE', 'G1', null, 'engineering change', 24),
  ('D05-01', 5, 'Meet Engineering', 'Meet the engineering lead: responsibilities and hand-offs.', 'PEOPLE', 'SESSION', 'KAM', 5, true, false, 'NONE', 'G1', null, null, 25),
  ('D05-02', 5, 'Meet NPD', 'Meet NPD: programme launch responsibilities.', 'PEOPLE', 'SESSION', 'KAM', 5, true, false, 'NONE', 'G1', null, null, 26),
  ('D05-03', 5, 'Meet Quality', 'Meet Quality: customer quality, 8D and PPAP owners.', 'PEOPLE', 'SESSION', 'KAM', 5, true, false, 'NONE', 'G1', null, null, 27),
  ('D05-04', 5, 'Meet SCM', 'Meet SCM: planning, schedules and supplier risk.', 'PEOPLE', 'SESSION', 'KAM', 5, true, false, 'NONE', 'G1', null, null, 28),
  ('D05-05', 5, 'Meet Plant', 'Meet the plant head: capacity and delivery performance.', 'PEOPLE', 'SESSION', 'KAM', 5, true, false, 'NONE', 'G1', null, null, 29),
  ('D05-06', 5, 'Meet Finance', 'Meet Finance: costing, margin and credit.', 'PEOPLE', 'SESSION', 'KAM', 5, true, false, 'NONE', 'G1', null, null, 30),
  ('D05-07', 5, 'Ownership mapping', 'Build your internal ownership map: who owns which decision.', 'PEOPLE', 'DELIVERABLE', 'KAM', 5, true, false, 'NONE', 'G1', null, null, 31),
  ('D05-08', 5, 'Knowledge-source walkthrough', 'Learn where approved SOPs, policies and customer data live — and use the Ask FirstGear assistant once.', 'PEOPLE', 'LEARNING', 'KAM', 5, true, false, 'NONE', 'G1', null, 'knowledge sources', 32),
  ('D06-01', 6, 'Account ownership model', 'Understand what the KAM owns versus what functions own.', 'GOVERNANCE', 'LEARNING', 'KAM', 6, true, false, 'NONE', 'G2', null, 'ownership model', 33),
  ('D06-02', 6, 'Governance calendar', 'Learn the account governance calendar: weekly, monthly and quarterly reviews.', 'GOVERNANCE', 'LEARNING', 'KAM', 6, true, false, 'NONE', 'G2', null, null, 34),
  ('D06-03', 6, 'KAM KPIs', 'Learn the KAM KPIs and how they are measured.', 'GOVERNANCE', 'LEARNING', 'KAM', 6, true, false, 'NONE', 'G2', null, 'KPIs', 35),
  ('D06-04', 6, 'Approval authority', 'Study the approval authority matrix — who can approve prices, terms and commitments.', 'GOVERNANCE', 'LEARNING', 'KAM', 6, true, false, 'NONE', 'G2', null, 'approval authority', 36),
  ('D06-05', 6, 'Escalation map', 'Learn the escalation map and response timelines.', 'GOVERNANCE', 'LEARNING', 'KAM', 6, true, false, 'NONE', 'G2', null, 'escalation', 37),
  ('D07-01', 7, 'RFQ intake', 'Learn how RFQs are logged, scoped and acknowledged.', 'PROCESS', 'LEARNING', 'KAM', 7, true, false, 'NONE', 'G2', null, 'RFQ', 38),
  ('D07-02', 7, 'Feasibility assessment', 'Understand technical and capacity feasibility review.', 'PROCESS', 'LEARNING', 'KAM', 7, true, false, 'NONE', 'G2', null, 'feasibility', 39),
  ('D07-03', 7, 'Cross-functional inputs', 'Know which inputs Engineering, SCM, Plant and Finance provide.', 'PROCESS', 'LEARNING', 'KAM', 7, true, false, 'NONE', 'G2', null, null, 40),
  ('D07-04', 7, 'Quotation workflow', 'Follow the quotation workflow from cost model to submission.', 'PROCESS', 'LEARNING', 'KAM', 7, true, false, 'NONE', 'G2', null, 'quotation', 41),
  ('D07-05', 7, 'Approval chain', 'Learn the quotation approval chain and thresholds.', 'GOVERNANCE', 'LEARNING', 'KAM', 7, true, false, 'NONE', 'G2', null, 'approval chain', 42),
  ('D08-01', 8, 'Cost build-up', 'Understand material, conversion, overhead and logistics cost build-up. Knowledge only.', 'PROCESS', 'LEARNING', 'KAM', 8, true, false, 'NONE', 'G2', null, 'cost build-up', 43),
  ('D08-02', 8, 'Tooling & development cost', 'Understand tooling and development cost recovery options.', 'PROCESS', 'LEARNING', 'KAM', 8, true, false, 'NONE', 'G2', null, 'tooling', 44),
  ('D08-03', 8, 'Margin logic', 'Understand margin targets and floor logic. Knowledge only — no live pricing.', 'PROCESS', 'LEARNING', 'KAM', 8, true, false, 'NONE', 'G2', null, 'margin', 45),
  ('D08-04', 8, 'Price-change mechanics', 'Understand index-linked adjustments, annual price-downs and claims.', 'PROCESS', 'LEARNING', 'KAM', 8, true, false, 'NONE', 'G2', null, 'price change', 46),
  ('D08-05', 8, 'Payment-term mechanics', 'Understand payment terms and their working-capital impact.', 'PROCESS', 'LEARNING', 'KAM', 8, true, false, 'NONE', 'G2', null, 'payment terms', 47),
  ('D08-06', 8, 'Negotiation preparation', 'Learn how to prepare a negotiation brief: BATNA, give-gets and approvals.', 'PROCESS', 'LEARNING', 'KAM', 8, true, false, 'NONE', 'G2', null, 'negotiation', 48),
  ('D09-01', 9, 'Nomination-to-SOP governance', 'Understand programme governance from nomination to start of production.', 'GOVERNANCE', 'LEARNING', 'KAM', 9, true, false, 'NONE', 'G2', null, 'SOP', 49),
  ('D09-02', 9, 'APQP/PPAP touchpoints', 'Identify where the KAM is accountable in APQP and PPAP.', 'GOVERNANCE', 'LEARNING', 'KAM', 9, true, false, 'NONE', 'G2', null, 'APQP', 50),
  ('D09-03', 9, 'Engineering changes', 'Understand customer- and supplier-initiated change handling.', 'GOVERNANCE', 'LEARNING', 'KAM', 9, true, false, 'NONE', 'G2', null, 'engineering change', 51),
  ('D09-04', 9, 'Complaint / 8D interface', 'Understand the 8D discipline and the KAM''s role in customer communication.', 'GOVERNANCE', 'LEARNING', 'KAM', 9, true, false, 'NONE', 'G2', null, '8D', 52),
  ('D10-01', 10, 'Mock RFQ', 'Complete a mock RFQ response pack with your mentor.', 'PROCESS', 'ACTIVITY', 'KAM', 10, true, false, 'NONE', 'G2', null, null, 53),
  ('D10-02', 10, 'Pricing scenario (practice)', 'Attempt the costing-challenge practice scenario. Knowledge practice only.', 'PROCESS', 'SCENARIO', 'KAM', 10, true, false, 'NONE', 'G2', 'scenario:SCN-COSTING', null, 54),
  ('D10-03', 10, 'Customer escalation walkthrough', 'Walk through a historic customer escalation with your mentor.', 'GOVERNANCE', 'SESSION', 'KAM', 10, true, false, 'NONE', 'G2', null, null, 55),
  ('D10-04', 10, 'Structured mentor feedback', 'Mentor records structured feedback on Days 1–10.', 'PEOPLE', 'REVIEW', 'MENTOR', 10, true, false, 'NONE', 'G2', null, null, 56),
  ('D10-05', 10, 'Interim knowledge check', 'Take the Day-10 interim knowledge check.', 'GOVERNANCE', 'ASSESSMENT', 'KAM', 10, true, false, 'NONE', 'G2', 'assessment:DAY10-CHECK', null, 57),
  ('D11-01', 11, 'OEM organisation', 'Document the customer''s organisation in Customer 360.', 'PEOPLE', 'DELIVERABLE', 'KAM', 11, true, false, 'NONE', 'G3', null, 'customer organisation', 58),
  ('D11-02', 11, 'Strategic context', 'Document the customer''s strategy, electrification plans and supplier strategy.', 'GOVERNANCE', 'DELIVERABLE', 'KAM', 11, true, false, 'NONE', 'G3', null, 'strategy', 59),
  ('D11-03', 11, 'Supplied parts & applications', 'Document supplied parts and their applications.', 'PRODUCT', 'DELIVERABLE', 'KAM', 11, true, false, 'NONE', 'G3', null, 'supplied parts', 60),
  ('D12-01', 12, 'Programmes', 'Document active and upcoming programmes.', 'PRODUCT', 'DELIVERABLE', 'KAM', 12, true, false, 'NONE', 'G3', null, 'programmes', 61),
  ('D12-02', 12, 'Volumes & pipeline', 'Document volumes and the opportunity pipeline.', 'PROCESS', 'DELIVERABLE', 'KAM', 12, true, false, 'NONE', 'G3', null, 'pipeline', 62),
  ('D12-03', 12, 'Customer 360 mentor check-in', 'Review your Customer 360 draft with your mentor.', 'PEOPLE', 'SESSION', 'KAM', 12, true, false, 'NONE', 'G3', null, null, 63),
  ('D13-01', 13, 'Purchasing contacts', 'Add purchasing stakeholders to the stakeholder map.', 'PEOPLE', 'DELIVERABLE', 'KAM', 13, true, false, 'NONE', 'G3', null, null, 64),
  ('D13-02', 13, 'Engineering contacts', 'Add engineering stakeholders.', 'PEOPLE', 'DELIVERABLE', 'KAM', 13, true, false, 'NONE', 'G3', null, null, 65),
  ('D13-03', 13, 'Quality contacts', 'Add quality stakeholders.', 'PEOPLE', 'DELIVERABLE', 'KAM', 13, true, false, 'NONE', 'G3', null, null, 66),
  ('D13-04', 13, 'SCM / plant contacts', 'Add SCM and plant stakeholders.', 'PEOPLE', 'DELIVERABLE', 'KAM', 13, true, false, 'NONE', 'G3', null, null, 67),
  ('D14-01', 14, 'Pricing history', 'Record pricing history from approved records only.', 'PROCESS', 'DELIVERABLE', 'KAM', 14, true, false, 'NONE', 'G3', null, 'pricing history', 68),
  ('D14-02', 14, 'Commercial history', 'Record commercial history: claims, terms, disputes.', 'PROCESS', 'DELIVERABLE', 'KAM', 14, true, false, 'NONE', 'G3', null, null, 69),
  ('D14-03', 14, 'Past commitments', 'Record open and past commitments with owners.', 'GOVERNANCE', 'DELIVERABLE', 'KAM', 14, true, false, 'NONE', 'G3', null, null, 70),
  ('D14-04', 14, 'Lessons learned & submit account brief', 'Record lessons learned and submit the account brief for mentor review.', 'GOVERNANCE', 'DELIVERABLE', 'KAM', 14, true, false, 'NONE', 'G3', 'brief:SUBMIT', null, 71),
  ('D15-01', 15, 'Four-pillar readiness assessment', 'Take the Day-15 four-pillar assessment. Weighted: Governance 25%, People 20%, Process 30%, Product 25% (configurable).', 'GOVERNANCE', 'ASSESSMENT', 'KAM', 15, true, false, 'NONE', 'G3', 'assessment:DAY15-READINESS', null, 72),
  ('D15-02', 15, 'Customer 360 review', 'Mentor reviews the Customer 360 and stakeholder map.', 'PEOPLE', 'REVIEW', 'MENTOR', 15, true, false, 'NONE', 'G3', 'review:CUSTOMER_360', null, 73),
  ('D15-03', 15, 'Account brief review', 'Mentor reviews and approves the account brief.', 'GOVERNANCE', 'REVIEW', 'MENTOR', 15, true, false, 'NONE', 'G3', 'review:ACCOUNT_BRIEF', null, 74),
  ('D16-01', 16, 'Observe customer review', 'Join a customer review as an observer.', 'PEOPLE', 'ACTIVITY', 'KAM', 16, true, false, 'CUSTOMER', 'G4', null, null, 75),
  ('D16-02', 16, 'Observe internal review', 'Join an internal account review as an observer.', 'PEOPLE', 'ACTIVITY', 'KAM', 16, true, false, 'NONE', 'G4', null, null, 76),
  ('D16-03', 16, 'Prepare minutes', 'Prepare the minutes of the observed reviews.', 'PROCESS', 'DELIVERABLE', 'KAM', 16, true, false, 'NONE', 'G4', null, null, 77),
  ('D17-01', 17, 'Prepare action tracker', 'Prepare the account action tracker with owners and dates.', 'PROCESS', 'DELIVERABLE', 'KAM', 17, true, false, 'NONE', 'G4', null, null, 78),
  ('D17-02', 17, 'Draft unsent customer responses', 'Draft responses to live customer mails — submitted for mentor review, not sent.', 'PROCESS', 'DELIVERABLE', 'KAM', 17, true, true, 'NONE', 'G4', null, null, 79),
  ('D18-01', 18, 'Handle routine customer queries', 'Handle selected routine customer queries (schedules, documentation).', 'PROCESS', 'ACTIVITY', 'KAM', 18, true, true, 'CUSTOMER', 'G4', null, null, 80),
  ('D18-02', 18, 'Mandatory pre-send review', 'Mentor reviews every outgoing response before it is sent.', 'GOVERNANCE', 'REVIEW', 'MENTOR', 18, true, false, 'NONE', 'G4', null, null, 81),
  ('D19-01', 19, 'Coordinate cross-functional closure', 'Drive closure of open actions across Quality, SCM, Plant and Engineering.', 'PEOPLE', 'ACTIVITY', 'KAM', 19, true, false, 'NONE', 'G4', null, null, 82),
  ('D20-01', 20, 'Lead account-action review', 'Lead one internal review covering quality, delivery, commercial and programme topics.', 'GOVERNANCE', 'ACTIVITY', 'KAM', 20, true, true, 'NONE', 'G4', null, null, 83),
  ('D20-02', 20, 'Mentor observation notes', 'Mentor records observations of the internal review.', 'PEOPLE', 'REVIEW', 'MENTOR', 20, true, false, 'NONE', 'G4', null, null, 84),
  ('D21-01', 21, 'Certification: RFQ response', 'Complete the RFQ-response certification scenario.', 'PROCESS', 'SCENARIO', 'KAM', 21, true, false, 'NONE', 'G4', 'scenario:SCN-RFQ', null, 85),
  ('D21-02', 21, 'Certification: price challenge', 'Complete the price-challenge certification scenario.', 'PROCESS', 'SCENARIO', 'KAM', 21, true, false, 'NONE', 'G4', 'scenario:SCN-PRICE', null, 86),
  ('D21-03', 21, 'Certification: delivery risk', 'Complete the delivery-risk certification scenario.', 'PROCESS', 'SCENARIO', 'KAM', 21, true, false, 'NONE', 'G4', 'scenario:SCN-DELIVERY', null, 87),
  ('D21-04', 21, 'Certification: quality escalation', 'Complete the quality-escalation certification scenario.', 'GOVERNANCE', 'SCENARIO', 'KAM', 21, true, false, 'NONE', 'G4', 'scenario:SCN-QUALITY', null, 88),
  ('D21-05', 21, 'Mentor certification review', 'Mentor reviews certification scenarios and decides the gate.', 'GOVERNANCE', 'REVIEW', 'MENTOR', 21, true, false, 'NONE', 'G4', 'gate:G4', null, 89),
  ('D22-01', 22, 'Prepare commercial position', 'Prepare a commercial position for joint discussion. No autonomous pricing.', 'PROCESS', 'DELIVERABLE', 'KAM', 22, true, true, 'PRICING', 'G5', null, null, 90),
  ('D23-01', 23, 'Reporting Boss reviews position', 'Reporting Boss reviews and challenges the position.', 'GOVERNANCE', 'REVIEW', 'REPORTING_BOSS', 23, true, false, 'PRICING', 'G5', null, null, 91),
  ('D24-01', 24, 'Joint live commercial discussion', 'Join a live commercial discussion jointly with the Reporting Boss.', 'PEOPLE', 'ACTIVITY', 'KAM', 24, true, false, 'PRICING', 'G5', null, null, 92),
  ('D25-01', 25, 'Draft negotiated position', 'Draft the follow-up position for Reporting Boss approval.', 'PROCESS', 'DELIVERABLE', 'KAM', 25, true, true, 'PRICING', 'G5', null, null, 93),
  ('D26-01', 26, 'Own agreed account scope', 'Own the agreed account scope; daily light-touch review.', 'PEOPLE', 'ACTIVITY', 'KAM', 26, true, false, 'CUSTOMER', 'G5', null, null, 94),
  ('D27-01', 27, 'Daily review log', 'Log daily review outcomes with your mentor.', 'PROCESS', 'ACTIVITY', 'KAM', 27, true, false, 'CUSTOMER', 'G5', null, null, 95),
  ('D28-01', 28, 'Alternate-day review log', 'Review cadence moves to alternate days.', 'PROCESS', 'ACTIVITY', 'KAM', 28, true, false, 'CUSTOMER', 'G5', null, null, 96),
  ('D29-01', 29, 'Assemble panel evidence', 'Assemble evidence: live cases, outputs, scenario results, dependency trend.', 'GOVERNANCE', 'DELIVERABLE', 'KAM', 29, true, false, 'NONE', 'G5', null, null, 97),
  ('D30-01', 30, 'Mentor panel input', 'Mentor submits panel input.', 'PEOPLE', 'REVIEW', 'MENTOR', 30, true, false, 'NONE', 'G5', 'panel:MENTOR', null, 98),
  ('D30-02', 30, 'HR panel input', 'HR submits panel input.', 'PEOPLE', 'REVIEW', 'HR_ADMIN', 30, true, false, 'NONE', 'G5', 'panel:HR', null, 99),
  ('D30-03', 30, 'Reporting Boss final sign-off', 'Reporting Boss records the final readiness decision.', 'GOVERNANCE', 'REVIEW', 'REPORTING_BOSS', 30, true, false, 'NONE', 'G5', 'panel:SIGNOFF', null, 100)
) as t(code, day_number, title, description, pillar, task_type, owner_role, due_day,
          is_mandatory, requires_approval, exposure, gate_code, action_ref, knowledge_topic, sort_order)
on conflict do nothing;

insert into public.task_dependencies (task_id, depends_on_task_id)
select t.id, d.id
from (values
  ('D05-07', 'D05-01'),
  ('D05-07', 'D05-03'),
  ('D05-07', 'D05-06'),
  ('D07-02', 'D07-01'),
  ('D07-03', 'D07-02'),
  ('D07-04', 'D07-03'),
  ('D07-05', 'D07-04'),
  ('D10-01', 'D07-05'),
  ('D10-02', 'D08-06'),
  ('D10-05', 'D10-01'),
  ('D14-04', 'D11-01'),
  ('D14-04', 'D11-02'),
  ('D14-04', 'D11-03'),
  ('D14-04', 'D12-01'),
  ('D14-04', 'D12-02'),
  ('D14-04', 'D14-01'),
  ('D14-04', 'D14-02'),
  ('D14-04', 'D14-03'),
  ('D15-02', 'D14-04'),
  ('D15-03', 'D14-04'),
  ('D18-02', 'D18-01'),
  ('D20-02', 'D20-01'),
  ('D21-05', 'D21-01'),
  ('D21-05', 'D21-02'),
  ('D21-05', 'D21-03'),
  ('D21-05', 'D21-04'),
  ('D23-01', 'D22-01'),
  ('D24-01', 'D23-01'),
  ('D25-01', 'D24-01'),
  ('D30-03', 'D30-01'),
  ('D30-03', 'D30-02')
) as x(task_code, dep_code)
join public.onboarding_templates tpl on tpl.code = 'KAM-30'
join public.tasks t on t.template_id = tpl.id and t.code = x.task_code
join public.tasks d on d.template_id = tpl.id and d.code = x.dep_code
on conflict do nothing;
