-- ════════════════════════════════════════════════════════════════════
-- FirstGear KAM Onboarding Compass — 002 seed onboarding programme
-- GENERATED by scripts/generate-seed-sql.ts from lib/seed-data — edit the source, then regenerate.
-- ════════════════════════════════════════════════════════════════════

insert into public.roles (id, name, description) values
  ('KAM','Key Account Manager','New or reassigned KAM in onboarding'),
  ('MENTOR','Mentor','Prior KAM / SME who coaches and reviews'),
  ('REPORTING_BOSS','Reporting Boss','KAM Head — final decision-maker for independent account handling'),
  ('HR_ADMIN','HR / Admin','Programme owner and administrator')
on conflict (id) do nothing;

insert into public.app_settings (key, value, category, label, description, value_type) values
  ('PROGRAMME_NAME', '"FirstGear KAM Onboarding Compass"'::jsonb, 'programme', 'Programme name', 'Displayed across the application.', 'string'),
  ('PROGRAMME_DURATION', '30'::jsonb, 'programme', 'Programme duration (days)', 'Length of the standard journey before any extension.', 'number'),
  ('ONBOARDING_START_OFFSET_DAYS', '0'::jsonb, 'programme', 'Onboarding start day (offset from joining)', 'Days after the joining date that Day 1 begins for new instances.', 'number'),
  ('DAY_COUNTING', '"CALENDAR"'::jsonb, 'programme', 'Day counting', 'CALENDAR or BUSINESS days for due/overdue calculation.', 'string'),
  ('GOVERNANCE_WEIGHT', '25'::jsonb, 'scoring', 'Governance weight (%)', 'Day-15 pillar weight. Pillar weights must total 100.', 'number'),
  ('PEOPLE_WEIGHT', '20'::jsonb, 'scoring', 'People weight (%)', 'Day-15 pillar weight.', 'number'),
  ('PROCESS_WEIGHT', '30'::jsonb, 'scoring', 'Process weight (%)', 'Day-15 pillar weight.', 'number'),
  ('PRODUCT_WEIGHT', '25'::jsonb, 'scoring', 'Product weight (%)', 'Day-15 pillar weight.', 'number'),
  ('DAY15_GREEN_THRESHOLD', '80'::jsonb, 'gates', 'Day-15 Green threshold (%)', 'Score at or above this is Green.', 'number'),
  ('DAY15_AMBER_THRESHOLD', '60'::jsonb, 'gates', 'Day-15 Amber threshold (%)', 'Score at or above this (and below Green) is Amber; below is Red.', 'number'),
  ('DAY10_PASS_THRESHOLD', '70'::jsonb, 'gates', 'Interim knowledge check pass (%)', 'Minimum interim knowledge-check score required before the Day-15 assessment.', 'number'),
  ('DAY21_PASS_THRESHOLD', '75'::jsonb, 'gates', 'Day-21 scenario test pass (%)', 'Minimum average certification score. Mentors cannot approve below this.', 'number'),
  ('DAY21_REQUIRED', 'true'::jsonb, 'gates', 'Day-21 scenario test required', 'Gate 2 (Day-21 scenario test) must pass before pricing or customer ownership.', 'boolean'),
  ('PRICING_GATE_REQUIRED', 'true'::jsonb, 'gates', 'Pricing gate required', 'Pricing exposure needs a Green Day-15 score and Reporting Boss approval.', 'boolean'),
  ('CUSTOMER_OWNERSHIP_GATE_REQUIRED', 'true'::jsonb, 'gates', 'Customer-ownership gate required', 'Guided customer ownership needs Reporting Boss approval.', 'boolean'),
  ('AMBER_REFRESH_DAYS', '4'::jsonb, 'remediation', 'Amber refresh length (days)', 'Targeted refresh length for Amber (3–5).', 'number'),
  ('RED_EXTENSION_DAYS', '10'::jsonb, 'remediation', 'Red extension (days)', 'Proposed onboarding extension for Red.', 'number'),
  ('READINESS_WEIGHTS', '{"tasks":30,"knowledge":30,"scenario":25,"gates":15}'::jsonb, 'scoring', 'Overall readiness composition (%)', 'How the dashboard ''overall readiness'' combines task completion, knowledge score, scenario score and gate progress. Must total 100.', 'json'),
  ('SUPPORT_CHAT_DAYS', '15'::jsonb, 'notifications', 'KAM support chat window (days)', 'Days from Day 1 during which a KAM can message their Mentor and HR in the Compass. The thread stays readable afterwards.', 'number'),
  ('REMINDER_LEAD_DAYS', '1'::jsonb, 'notifications', 'Reminder lead time (days)', 'How far ahead sessions, assessments and gates are flagged.', 'number'),
  ('SESSION_TYPES', '["HR Orientation","Mentor Check-in","Product Training","Process Training","Plant Walk","Customer 360 Review","Manager Review","Assessment","Scenario Certification","Readiness Panel"]'::jsonb, 'sessions', 'Session types', 'Session types available when scheduling.', 'json'),
  ('KNOWLEDGE_CATEGORIES', '["Company","Products","Customers","Sales","Processes","Training","Policies","Quality","Governance","Account"]'::jsonb, 'knowledge', 'Knowledge categories', 'Categories available for knowledge documents.', 'json'),
  ('RAG_TOP_K', '6'::jsonb, 'knowledge', 'Retrieved passages per answer', 'Number of passages passed to the generator.', 'number'),
  ('RAG_MIN_SIMILARITY', '0.35'::jsonb, 'knowledge', 'Minimum retrieval similarity', 'Below this, the assistant says evidence is insufficient instead of answering.', 'number')
on conflict (key) do nothing;

insert into public.onboarding_templates (code, name, description, duration_days)
values ('KAM-30', 'KAM 30-Day Readiness Journey', 'Guided, evidence-based onboarding for new or reassigned Key Account Managers. Days 1–15 learn the company; Days 16–30 guided ownership controlled by readiness gates.', 30)
on conflict (code) do nothing;

with tpl as (select id from public.onboarding_templates where code = 'KAM-30')
insert into public.onboarding_days (template_id, day_number, phase, segment, title, pillars, objectives, resources, gate_code)
select tpl.id, d.* from tpl, (values
  (1, 1, 'Governance', 'Company, conduct & KAM charter', array['GOVERNANCE']::text[], array['Understand the company: history, footprint, financials and strategy','Know the code of conduct: gifts, anti-bribery, competition law, confidentiality','Understand the KAM charter: purpose, scope and accountability']::text[], '[{"label":"Company overview","document_key":"COMPANY-OVERVIEW"},{"label":"Code of conduct","document_key":"CODE-OF-CONDUCT"},{"label":"KAM charter","document_key":"KAM-CHARTER"},{"label":"FAQ — Company, products & markets","document_key":"FAQ-COMPANY-PRODUCTS"},{"label":"FAQ — Onboarding journey & app","document_key":"FAQ-ONBOARDING"}]'::jsonb, null),
  (2, 1, 'Governance', 'KAM charter, KPIs & approval authority', array['GOVERNANCE']::text[], array['Understand the account ownership model','Know the governance calendar and KAM KPIs','Know the approval authority matrix and the escalation map']::text[], '[{"label":"KAM charter","document_key":"KAM-CHARTER"},{"label":"Approval authority matrix","document_key":"APPROVAL-MATRIX"},{"label":"Escalation playbook","document_key":"ESCALATION-PLAYBOOK"},{"label":"FAQ — Account ownership, governance & conduct","document_key":"FAQ-ACCOUNT-MANAGEMENT"}]'::jsonb, null),
  (3, 1, 'Governance', 'Quality & change governance', array['GOVERNANCE']::text[], array['Understand customer-specific requirements (CSRs)','Know complaint-handling timelines and engineering change control','Walk through a historic customer escalation']::text[], '[{"label":"Quality governance manual","document_key":"QUALITY-GOVERNANCE"},{"label":"Escalation playbook","document_key":"ESCALATION-PLAYBOOK"},{"label":"FAQ — Quality, programmes, delivery & escalation","document_key":"FAQ-QUALITY-DELIVERY"}]'::jsonb, null),
  (4, 1, 'Governance', 'Programme governance & customer commitments', array['GOVERNANCE']::text[], array['Understand nomination-to-SOP governance and KAM touchpoints','Know the APQP/PPAP, engineering-change and 8D interfaces','Record the customer''s strategic context and past commitments']::text[], '[{"label":"Programme governance guide","document_key":"PROGRAMME-GOVERNANCE"},{"label":"Quality governance manual","document_key":"QUALITY-GOVERNANCE"},{"label":"Customer 360 — Northwind Motors","document_key":"C360-NORTHWIND"}]'::jsonb, null),
  (5, 1, 'People', 'Values, HR & your manager', array['PEOPLE']::text[], array['Live the values: Integrity, Vitality, Frugality, Agility','Complete HR orientation and onboarding setup','Agree 30-day expectations with the Reporting Boss']::text[], '[{"label":"Company overview","document_key":"COMPANY-OVERVIEW"},{"label":"FAQ — Onboarding journey & app","document_key":"FAQ-ONBOARDING"}]'::jsonb, null),
  (6, 1, 'People', 'Meet the functions', array['PEOPLE']::text[], array['Know who owns what across Engineering, NPD, Quality, SCM, Plant and Finance','Know the hand-offs between each function and the KAM']::text[], '[{"label":"Ownership map & knowledge sources","document_key":"ORG-NAVIGATION"},{"label":"FAQ — Account ownership, governance & conduct","document_key":"FAQ-ACCOUNT-MANAGEMENT"}]'::jsonb, null),
  (7, 1, 'People', 'Ownership map & customer stakeholders', array['PEOPLE']::text[], array['Build your internal ownership map','Know where approved knowledge lives','Map the customer organisation and stakeholders']::text[], '[{"label":"Ownership map & knowledge sources","document_key":"ORG-NAVIGATION"},{"label":"Customer 360 — Northwind Motors","document_key":"C360-NORTHWIND"},{"label":"FAQ — Account ownership, governance & conduct","document_key":"FAQ-ACCOUNT-MANAGEMENT"}]'::jsonb, null),
  (8, 1, 'Product', 'Product portfolio', array['PRODUCT']::text[], array['Explain the driveline, motor, sensor and railway product lines','Map products to ICE, hybrid and BEV powertrains']::text[], '[{"label":"Product portfolio guide","document_key":"PRODUCT-PORTFOLIO"},{"label":"FAQ — Company, products & markets","document_key":"FAQ-COMPANY-PRODUCTS"}]'::jsonb, null),
  (9, 1, 'Product', 'Markets & customer products', array['PRODUCT']::text[], array['Map products to segments and end markets','Record the customer''s supplied parts and programmes']::text[], '[{"label":"Product portfolio guide","document_key":"PRODUCT-PORTFOLIO"},{"label":"Customer 360 — Northwind Motors","document_key":"C360-NORTHWIND"}]'::jsonb, null),
  (10, 1, 'Process', 'Plant & manufacturing', array['PROCESS']::text[], array['Walk the plant and follow the manufacturing flow','Understand critical operations, traceability and logistics','Adopt the safety and quality mindset']::text[], '[{"label":"Manufacturing process overview","document_key":"MFG-PROCESS"},{"label":"FAQ — Quality, programmes, delivery & escalation","document_key":"FAQ-QUALITY-DELIVERY"}]'::jsonb, null),
  (11, 1, 'Process', 'APQP, PPAP & RFQ to quotation', array['PROCESS']::text[], array['Explain APQP phases and PPAP levels','Follow an RFQ from intake to approved quotation']::text[], '[{"label":"Quality governance manual","document_key":"QUALITY-GOVERNANCE"},{"label":"RFQ to quotation SOP","document_key":"RFQ-SOP"},{"label":"FAQ — RFQs, costing, pricing & approvals","document_key":"FAQ-COMMERCIAL"}]'::jsonb, null),
  (12, 1, 'Process', 'Costing & commercials (knowledge only)', array['PROCESS']::text[], array['Explain cost build-up, tooling and margin logic','Understand price-change and payment-term mechanics','Prepare for negotiation — no live pricing decisions']::text[], '[{"label":"Costing & commercial mechanics","document_key":"COSTING-COMMERCIALS"},{"label":"FAQ — RFQs, costing, pricing & approvals","document_key":"FAQ-COMMERCIAL"}]'::jsonb, null),
  (13, 1, 'Process', 'Practice & interim check', array['PROCESS','GOVERNANCE']::text[], array['Run a mock RFQ and a pricing scenario','Pass the interim knowledge check on all four pillars']::text[], '[{"label":"RFQ to quotation SOP","document_key":"RFQ-SOP"},{"label":"Costing & commercial mechanics","document_key":"COSTING-COMMERCIALS"},{"label":"Assessment guide","document_key":"ASSESSMENT-GUIDE"}]'::jsonb, null),
  (14, 1, 'Process', 'Commercial history & account brief', array['PROCESS','GOVERNANCE']::text[], array['Record volumes, pipeline, pricing and commercial history from approved records','Submit the account brief for mentor review']::text[], '[{"label":"Customer 360 — Northwind Motors","document_key":"C360-NORTHWIND"},{"label":"Costing & commercial mechanics","document_key":"COSTING-COMMERCIALS"}]'::jsonb, null),
  (15, 1, 'Day-15 gate', 'Day-15 gate — readiness assessment', array['GOVERNANCE','PEOPLE','PROCESS','PRODUCT']::text[], array['Complete the four-pillar assessment','Customer 360 and account brief reviewed by Mentor','Readiness score ≥ 80% (Green) opens Phase 2']::text[], '[{"label":"Assessment guide","document_key":"ASSESSMENT-GUIDE"},{"label":"FAQ — Onboarding journey & app","document_key":"FAQ-ONBOARDING"}]'::jsonb, 'G1'),
  (16, 2, 'Shadow reviews', 'Shadow customer & internal reviews', array['PEOPLE','PROCESS']::text[], array['Observe reviews and prepare minutes and action trackers']::text[], '[{"label":"Escalation playbook","document_key":"ESCALATION-PLAYBOOK"}]'::jsonb, null),
  (17, 2, 'Shadow reviews', 'Draft (unsent) customer responses', array['PROCESS']::text[], array['Draft responses for mentor review — nothing is sent']::text[], '[]'::jsonb, null),
  (18, 2, 'Own low-risk queries', 'Routine customer queries', array['PROCESS','PEOPLE']::text[], array['Handle selected routine queries with mandatory pre-send review']::text[], '[]'::jsonb, null),
  (19, 2, 'Own low-risk queries', 'Coordinate cross-functional closure', array['PEOPLE']::text[], array['Drive closure across Quality, SCM, Plant and Engineering']::text[], '[]'::jsonb, null),
  (20, 2, 'Lead an internal review', 'Lead account-action review', array['GOVERNANCE','PROCESS']::text[], array['Lead one review covering quality, delivery, commercial and programme topics — Mentor observes']::text[], '[]'::jsonb, null),
  (21, 2, 'Scenario test (gate)', 'Scenario test (gate)', array['PROCESS','GOVERNANCE']::text[], array['RFQ response, price challenge, delivery risk, quality escalation','Score against Day-15 baseline']::text[], '[{"label":"Escalation playbook","document_key":"ESCALATION-PLAYBOOK"},{"label":"RFQ to quotation SOP","document_key":"RFQ-SOP"}]'::jsonb, 'G2'),
  (22, 2, 'Guided pricing', 'Prepare pricing position', array['PROCESS']::text[], array['Prepare a commercial position for joint discussion']::text[], '[{"label":"Costing & commercial mechanics","document_key":"COSTING-COMMERCIALS"},{"label":"Approval authority matrix","document_key":"APPROVAL-MATRIX"}]'::jsonb, null),
  (23, 2, 'Guided pricing', 'Reporting Boss reviews position', array['GOVERNANCE']::text[], array['Reporting Boss reviews and challenges the position']::text[], '[]'::jsonb, null),
  (24, 2, 'Guided pricing', 'Joint commercial discussion', array['PROCESS','PEOPLE']::text[], array['Join a live commercial discussion with the Reporting Boss']::text[], '[]'::jsonb, null),
  (25, 2, 'Guided pricing', 'Draft negotiated position', array['PROCESS']::text[], array['Draft the follow-up position for Reporting Boss approval']::text[], '[]'::jsonb, null),
  (26, 2, 'Own the account', 'Own agreed account scope', array['PEOPLE','PROCESS']::text[], array['Own the agreed scope with daily light-touch review']::text[], '[]'::jsonb, null),
  (27, 2, 'Own the account', 'Ownership — daily review', array['PROCESS']::text[], array['Continue ownership; daily review']::text[], '[]'::jsonb, null),
  (28, 2, 'Own the account', 'Ownership — alternate-day review', array['PROCESS']::text[], array['Review cadence moves to alternate days']::text[], '[]'::jsonb, null),
  (29, 2, 'Own the account', 'Prepare panel evidence', array['GOVERNANCE']::text[], array['Assemble evidence of live-case performance and outputs']::text[], '[]'::jsonb, null),
  (30, 2, 'Readiness panel sign-off', 'Readiness panel sign-off', array['GOVERNANCE','PEOPLE','PROCESS','PRODUCT']::text[], array['Panel evaluates knowledge, response quality, dependency reduction, live cases, scenarios and account understanding','Reporting Boss records the final human decision']::text[], '[]'::jsonb, 'G3')
) as d(day_number, phase, segment, title, pillars, objectives, resources, gate_code)
on conflict (template_id, day_number) do nothing;

with tpl as (select id from public.onboarding_templates where code = 'KAM-30')
insert into public.gate_definitions (template_id, code, day_number, name, description, gate_type, approver_role, unlocks, sort_order)
select tpl.id, g.* from tpl, (values
  ('G1', 15, 'Day-15 gate — readiness score ≥ 80%', 'Phase 1 (Days 1–15) learning across Governance, People, Process and Product complete, interim knowledge check passed, Customer 360 and account brief reviewed by the Mentor, and a weighted four-pillar readiness score at or above the Green threshold (80%).', 'ASSESSMENT', 'MENTOR', array['PHASE_2']::text[], 1),
  ('G2', 21, 'Scenario test', 'RFQ response, price challenge, delivery risk and quality escalation scenarios scored against the Day-15 baseline and certified by the Mentor.', 'SCENARIO', 'MENTOR', array['PRICING_ELIGIBLE','CUSTOMER_ELIGIBLE']::text[], 2),
  ('G3', 30, 'Readiness panel sign-off', 'Reporting Boss, Mentor and HR panel. The Reporting Boss records the final, human-certified readiness decision.', 'PANEL', 'REPORTING_BOSS', array['INDEPENDENT_HANDLING']::text[], 3)
) as g(code, day_number, name, description, gate_type, approver_role, unlocks, sort_order)
on conflict (template_id, code) do nothing;

with tpl as (select id from public.onboarding_templates where code = 'KAM-30')
insert into public.tasks (template_id, code, day_number, title, description, pillar, task_type, owner_role, due_day,
                          is_mandatory, requires_approval, exposure, gate_code, action_ref, knowledge_topic, sort_order)
select tpl.id, t.* from tpl, (values
  ('D01-01', 1, 'Company profile', 'Read the company profile: history, businesses, 12 plants, FY2022-23 to FY2025-26 financials, order book, markets and the four strategic priorities.', 'GOVERNANCE', 'LEARNING', 'KAM', 1, true, false, 'NONE', 'G1', null, 'company', 1),
  ('D01-03', 1, 'Code of conduct', 'Read and acknowledge the code of conduct, including gifts, hospitality and confidentiality.', 'GOVERNANCE', 'LEARNING', 'KAM', 1, true, false, 'NONE', 'G1', null, 'conduct', 2),
  ('D01-05', 1, 'KAM charter introduction', 'Read the KAM charter introduction: purpose, scope and accountability.', 'GOVERNANCE', 'LEARNING', 'KAM', 1, true, false, 'NONE', 'G1', null, 'charter', 3),
  ('D06-01', 2, 'Account ownership model', 'Understand what the KAM owns versus what functions own.', 'GOVERNANCE', 'LEARNING', 'KAM', 2, true, false, 'NONE', 'G1', null, 'ownership model', 4),
  ('D06-02', 2, 'Governance calendar', 'Learn the account governance calendar: weekly, monthly and quarterly reviews.', 'GOVERNANCE', 'LEARNING', 'KAM', 2, true, false, 'NONE', 'G1', null, null, 5),
  ('D06-03', 2, 'KAM KPIs', 'Learn the KAM KPIs and how they are measured.', 'GOVERNANCE', 'LEARNING', 'KAM', 2, true, false, 'NONE', 'G1', null, 'KPIs', 6),
  ('D06-04', 2, 'Approval authority', 'Study the approval authority matrix — who can approve prices, terms and commitments.', 'GOVERNANCE', 'LEARNING', 'KAM', 2, true, false, 'NONE', 'G1', null, 'approval authority', 7),
  ('D06-05', 2, 'Escalation map', 'Learn the escalation map and response timelines.', 'GOVERNANCE', 'LEARNING', 'KAM', 2, true, false, 'NONE', 'G1', null, 'escalation', 8),
  ('D04-01', 3, 'Customer-specific quality mindset', 'Study customer-specific requirements (CSRs) for key OEMs.', 'GOVERNANCE', 'LEARNING', 'KAM', 3, true, false, 'NONE', 'G1', null, 'CSR', 9),
  ('D04-04', 3, 'Complaint handling', 'Understand the complaint-handling process and response timelines.', 'GOVERNANCE', 'LEARNING', 'KAM', 3, true, false, 'NONE', 'G1', null, 'complaints', 10),
  ('D04-05', 3, 'Engineering change-control governance', 'Understand how engineering changes are requested, approved and communicated.', 'GOVERNANCE', 'LEARNING', 'KAM', 3, true, false, 'NONE', 'G1', null, 'engineering change', 11),
  ('D10-03', 3, 'Customer escalation walkthrough', 'Walk through a historic customer escalation with your mentor.', 'GOVERNANCE', 'SESSION', 'KAM', 3, true, false, 'NONE', 'G1', null, null, 12),
  ('D09-01', 4, 'Nomination-to-SOP governance', 'Understand programme governance from nomination to start of production.', 'GOVERNANCE', 'LEARNING', 'KAM', 4, true, false, 'NONE', 'G1', null, 'SOP', 13),
  ('D09-02', 4, 'APQP/PPAP touchpoints', 'Identify where the KAM is accountable in APQP and PPAP.', 'GOVERNANCE', 'LEARNING', 'KAM', 4, true, false, 'NONE', 'G1', null, 'APQP', 14),
  ('D09-03', 4, 'Engineering changes', 'Understand customer- and supplier-initiated change handling.', 'GOVERNANCE', 'LEARNING', 'KAM', 4, true, false, 'NONE', 'G1', null, 'engineering change', 15),
  ('D09-04', 4, 'Complaint / 8D interface', 'Understand the 8D discipline and the KAM''s role in customer communication.', 'GOVERNANCE', 'LEARNING', 'KAM', 4, true, false, 'NONE', 'G1', null, '8D', 16),
  ('D11-02', 4, 'Strategic context', 'Document the customer''s strategy, electrification plans and supplier strategy.', 'GOVERNANCE', 'DELIVERABLE', 'KAM', 4, true, false, 'NONE', 'G1', null, 'strategy', 17),
  ('D14-03', 4, 'Past commitments', 'Record open and past commitments with owners.', 'GOVERNANCE', 'DELIVERABLE', 'KAM', 4, true, false, 'NONE', 'G1', null, null, 18),
  ('D01-02', 5, 'Company values', 'Review the values — Integrity, Vitality, Frugality, Agility — and how they show up in customer work.', 'PEOPLE', 'LEARNING', 'KAM', 5, true, false, 'NONE', 'G1', null, 'values', 19),
  ('D01-04', 5, 'HR orientation', 'Attend HR orientation: policies, leave, benefits and ways of working.', 'PEOPLE', 'SESSION', 'KAM', 5, true, false, 'NONE', 'G1', null, null, 20),
  ('D01-06', 5, 'Manager expectations', 'Meet the Reporting Boss to agree expectations for the first 30 days.', 'PEOPLE', 'SESSION', 'KAM', 5, true, false, 'NONE', 'G1', null, null, 21),
  ('D01-07', 5, 'Initial onboarding setup', 'Confirm your onboarding profile, mentor and session calendar in the Compass. (IT access is handled separately by IT.)', 'PEOPLE', 'ACTIVITY', 'KAM', 5, true, false, 'NONE', 'G1', null, null, 22),
  ('D05-01', 6, 'Meet Engineering', 'Meet the engineering lead: responsibilities and hand-offs.', 'PEOPLE', 'SESSION', 'KAM', 6, true, false, 'NONE', 'G1', null, null, 23),
  ('D05-02', 6, 'Meet NPD', 'Meet NPD: programme launch responsibilities.', 'PEOPLE', 'SESSION', 'KAM', 6, true, false, 'NONE', 'G1', null, null, 24),
  ('D05-03', 6, 'Meet Quality', 'Meet Quality: customer quality, 8D and PPAP owners.', 'PEOPLE', 'SESSION', 'KAM', 6, true, false, 'NONE', 'G1', null, null, 25),
  ('D05-04', 6, 'Meet SCM', 'Meet SCM: planning, schedules and supplier risk.', 'PEOPLE', 'SESSION', 'KAM', 6, true, false, 'NONE', 'G1', null, null, 26),
  ('D05-05', 6, 'Meet Plant', 'Meet the plant head: capacity and delivery performance.', 'PEOPLE', 'SESSION', 'KAM', 6, true, false, 'NONE', 'G1', null, null, 27),
  ('D05-06', 6, 'Meet Finance', 'Meet Finance: costing, margin and credit.', 'PEOPLE', 'SESSION', 'KAM', 6, true, false, 'NONE', 'G1', null, null, 28),
  ('D05-07', 7, 'Ownership mapping', 'Build your internal ownership map: who owns which decision.', 'PEOPLE', 'DELIVERABLE', 'KAM', 7, true, false, 'NONE', 'G1', null, null, 29),
  ('D05-08', 7, 'Knowledge-source walkthrough', 'Learn where approved SOPs, policies and customer data live — and use the Ask FirstGear assistant once.', 'PEOPLE', 'LEARNING', 'KAM', 7, true, false, 'NONE', 'G1', null, 'knowledge sources', 30),
  ('D11-01', 7, 'OEM organisation', 'Document the customer''s organisation in Customer 360.', 'PEOPLE', 'DELIVERABLE', 'KAM', 7, true, false, 'NONE', 'G1', null, 'customer organisation', 31),
  ('D13-01', 7, 'Purchasing contacts', 'Add purchasing stakeholders to the stakeholder map.', 'PEOPLE', 'DELIVERABLE', 'KAM', 7, true, false, 'NONE', 'G1', null, null, 32),
  ('D13-02', 7, 'Engineering contacts', 'Add engineering stakeholders.', 'PEOPLE', 'DELIVERABLE', 'KAM', 7, true, false, 'NONE', 'G1', null, null, 33),
  ('D13-03', 7, 'Quality contacts', 'Add quality stakeholders.', 'PEOPLE', 'DELIVERABLE', 'KAM', 7, true, false, 'NONE', 'G1', null, null, 34),
  ('D13-04', 7, 'SCM / plant contacts', 'Add SCM and plant stakeholders.', 'PEOPLE', 'DELIVERABLE', 'KAM', 7, true, false, 'NONE', 'G1', null, null, 35),
  ('D12-03', 7, 'Customer 360 mentor check-in', 'Review your Customer 360 draft with your mentor.', 'PEOPLE', 'SESSION', 'KAM', 7, true, false, 'NONE', 'G1', null, null, 36),
  ('D02-01', 8, 'Driveline and ICE products', 'Study differential bevel gears, differential assemblies and starter motors — the driveline and ICE core, and the company''s global market shares.', 'PRODUCT', 'LEARNING', 'KAM', 8, true, false, 'NONE', 'G1', null, 'ICE', 37),
  ('D02-02', 8, 'Hybrid products', 'Study micro-hybrid starter motors, belt starter generators and hybrid-platform differential assemblies, and where they differ from ICE.', 'PRODUCT', 'LEARNING', 'KAM', 8, true, false, 'NONE', 'G1', null, 'hybrid', 38),
  ('D02-03', 8, 'BEV products', 'Study EV differential assemblies with final-drive gear, traction motors, controllers and active-suspension motor controllers, and why EV gears need tighter NVH.', 'PRODUCT', 'LEARNING', 'KAM', 8, true, false, 'NONE', 'G1', null, 'BEV', 39),
  ('D02-04', 9, 'Segments and end markets', 'Map products to passenger, commercial, off-highway, electric 2W/3W and railway segments, and to the India / Europe / North America / Asia revenue mix.', 'PRODUCT', 'LEARNING', 'KAM', 9, true, false, 'NONE', 'G1', null, 'segments', 40),
  ('D02-05', 9, 'Sensors, railway and new verticals', 'Understand radar sensors, railway systems and robotics, and the customer problems each product line solves.', 'PRODUCT', 'LEARNING', 'KAM', 9, true, false, 'NONE', 'G1', null, 'applications', 41),
  ('D11-03', 9, 'Supplied parts & applications', 'Document supplied parts and their applications.', 'PRODUCT', 'DELIVERABLE', 'KAM', 9, true, false, 'NONE', 'G1', null, 'supplied parts', 42),
  ('D12-01', 9, 'Programmes', 'Document active and upcoming programmes.', 'PRODUCT', 'DELIVERABLE', 'KAM', 9, true, false, 'NONE', 'G1', null, 'programmes', 43),
  ('D03-01', 10, 'Plant walk', 'Walk the plant with the plant lead and follow one part from raw material to dispatch.', 'PROCESS', 'SESSION', 'KAM', 10, true, false, 'NONE', 'G1', null, null, 44),
  ('D03-02', 10, 'Manufacturing process flow', 'Learn the end-to-end manufacturing flow.', 'PROCESS', 'LEARNING', 'KAM', 10, true, false, 'NONE', 'G1', null, 'process flow', 45),
  ('D03-03', 10, 'Critical operations', 'Identify the critical operations and special characteristics.', 'PROCESS', 'LEARNING', 'KAM', 10, true, false, 'NONE', 'G1', null, 'critical operations', 46),
  ('D03-04', 10, 'Traceability', 'Understand lot traceability and how it supports containment.', 'PROCESS', 'LEARNING', 'KAM', 10, true, false, 'NONE', 'G1', null, 'traceability', 47),
  ('D03-05', 10, 'Logistics', 'Understand inbound and outbound logistics, packaging and schedules.', 'PROCESS', 'LEARNING', 'KAM', 10, true, false, 'NONE', 'G1', null, 'logistics', 48),
  ('D03-06', 10, 'Safety mindset', 'Complete the safety induction and understand plant safety rules.', 'PROCESS', 'LEARNING', 'KAM', 10, true, false, 'NONE', 'G1', null, null, 49),
  ('D03-07', 10, 'Quality mindset', 'Understand the zero-defect mindset and the cost of poor quality.', 'PROCESS', 'LEARNING', 'KAM', 10, true, false, 'NONE', 'G1', null, null, 50),
  ('D04-02', 11, 'APQP overview', 'Learn the five APQP phases and the KAM''s touchpoints.', 'PROCESS', 'LEARNING', 'KAM', 11, true, false, 'NONE', 'G1', null, 'APQP', 51),
  ('D04-03', 11, 'PPAP overview', 'Learn PPAP submission levels and elements.', 'PROCESS', 'LEARNING', 'KAM', 11, true, false, 'NONE', 'G1', null, 'PPAP', 52),
  ('D07-01', 11, 'RFQ intake', 'Learn how RFQs are logged, scoped and acknowledged.', 'PROCESS', 'LEARNING', 'KAM', 11, true, false, 'NONE', 'G1', null, 'RFQ', 53),
  ('D07-02', 11, 'Feasibility assessment', 'Understand technical and capacity feasibility review.', 'PROCESS', 'LEARNING', 'KAM', 11, true, false, 'NONE', 'G1', null, 'feasibility', 54),
  ('D07-03', 11, 'Cross-functional inputs', 'Know which inputs Engineering, SCM, Plant and Finance provide.', 'PROCESS', 'LEARNING', 'KAM', 11, true, false, 'NONE', 'G1', null, null, 55),
  ('D07-04', 11, 'Quotation workflow', 'Follow the quotation workflow from cost model to submission.', 'PROCESS', 'LEARNING', 'KAM', 11, true, false, 'NONE', 'G1', null, 'quotation', 56),
  ('D07-05', 11, 'Approval chain', 'Learn the quotation approval chain and thresholds.', 'GOVERNANCE', 'LEARNING', 'KAM', 11, true, false, 'NONE', 'G1', null, 'approval chain', 57),
  ('D08-01', 12, 'Cost build-up', 'Understand material, conversion, overhead and logistics cost build-up. Knowledge only.', 'PROCESS', 'LEARNING', 'KAM', 12, true, false, 'NONE', 'G1', null, 'cost build-up', 58),
  ('D08-02', 12, 'Tooling & development cost', 'Understand tooling and development cost recovery options.', 'PROCESS', 'LEARNING', 'KAM', 12, true, false, 'NONE', 'G1', null, 'tooling', 59),
  ('D08-03', 12, 'Margin logic', 'Understand margin targets and floor logic. Knowledge only — no live pricing.', 'PROCESS', 'LEARNING', 'KAM', 12, true, false, 'NONE', 'G1', null, 'margin', 60),
  ('D08-04', 12, 'Price-change mechanics', 'Understand index-linked adjustments, annual price-downs and claims.', 'PROCESS', 'LEARNING', 'KAM', 12, true, false, 'NONE', 'G1', null, 'price change', 61),
  ('D08-05', 12, 'Payment-term mechanics', 'Understand payment terms and their working-capital impact.', 'PROCESS', 'LEARNING', 'KAM', 12, true, false, 'NONE', 'G1', null, 'payment terms', 62),
  ('D08-06', 12, 'Negotiation preparation', 'Learn how to prepare a negotiation brief: BATNA, give-gets and approvals.', 'PROCESS', 'LEARNING', 'KAM', 12, true, false, 'NONE', 'G1', null, 'negotiation', 63),
  ('D10-01', 13, 'Mock RFQ', 'Complete a mock RFQ response pack with your mentor.', 'PROCESS', 'ACTIVITY', 'KAM', 13, true, false, 'NONE', 'G1', null, null, 64),
  ('D10-02', 13, 'Pricing scenario (practice)', 'Attempt the costing-challenge practice scenario. Knowledge practice only.', 'PROCESS', 'SCENARIO', 'KAM', 13, true, false, 'NONE', 'G1', 'scenario:SCN-COSTING', null, 65),
  ('D10-04', 13, 'Structured mentor feedback', 'Mentor records structured feedback on Phase-1 learning so far.', 'PEOPLE', 'REVIEW', 'MENTOR', 13, true, false, 'NONE', 'G1', null, null, 66),
  ('D10-05', 13, 'Interim knowledge check', 'Take the interim knowledge check on Governance, People, Product and Process.', 'GOVERNANCE', 'ASSESSMENT', 'KAM', 13, true, false, 'NONE', 'G1', 'assessment:DAY10-CHECK', null, 67),
  ('D12-02', 14, 'Volumes & pipeline', 'Document volumes and the opportunity pipeline.', 'PROCESS', 'DELIVERABLE', 'KAM', 14, true, false, 'NONE', 'G1', null, 'pipeline', 68),
  ('D14-01', 14, 'Pricing history', 'Record pricing history from approved records only.', 'PROCESS', 'DELIVERABLE', 'KAM', 14, true, false, 'NONE', 'G1', null, 'pricing history', 69),
  ('D14-02', 14, 'Commercial history', 'Record commercial history: claims, terms, disputes.', 'PROCESS', 'DELIVERABLE', 'KAM', 14, true, false, 'NONE', 'G1', null, null, 70),
  ('D14-04', 14, 'Lessons learned & submit account brief', 'Record lessons learned and submit the account brief for mentor review.', 'GOVERNANCE', 'DELIVERABLE', 'KAM', 14, true, false, 'NONE', 'G1', 'brief:SUBMIT', null, 71),
  ('D15-01', 15, 'Four-pillar readiness assessment', 'Take the Day-15 four-pillar assessment. Weighted: Governance 25%, People 20%, Process 30%, Product 25% (configurable).', 'GOVERNANCE', 'ASSESSMENT', 'KAM', 15, true, false, 'NONE', 'G1', 'assessment:DAY15-READINESS', null, 72),
  ('D15-02', 15, 'Customer 360 review', 'Mentor reviews the Customer 360 and stakeholder map.', 'PEOPLE', 'REVIEW', 'MENTOR', 15, true, false, 'NONE', 'G1', 'review:CUSTOMER_360', null, 73),
  ('D15-03', 15, 'Account brief review', 'Mentor reviews and approves the account brief.', 'GOVERNANCE', 'REVIEW', 'MENTOR', 15, true, false, 'NONE', 'G1', 'review:ACCOUNT_BRIEF', null, 74),
  ('D16-01', 16, 'Observe customer review', 'Join a customer review as an observer.', 'PEOPLE', 'ACTIVITY', 'KAM', 16, true, false, 'CUSTOMER', 'G2', null, null, 75),
  ('D16-02', 16, 'Observe internal review', 'Join an internal account review as an observer.', 'PEOPLE', 'ACTIVITY', 'KAM', 16, true, false, 'NONE', 'G2', null, null, 76),
  ('D16-03', 16, 'Prepare minutes', 'Prepare the minutes of the observed reviews.', 'PROCESS', 'DELIVERABLE', 'KAM', 16, true, false, 'NONE', 'G2', null, null, 77),
  ('D17-01', 17, 'Prepare action tracker', 'Prepare the account action tracker with owners and dates.', 'PROCESS', 'DELIVERABLE', 'KAM', 17, true, false, 'NONE', 'G2', null, null, 78),
  ('D17-02', 17, 'Draft unsent customer responses', 'Draft responses to live customer mails — submitted for mentor review, not sent.', 'PROCESS', 'DELIVERABLE', 'KAM', 17, true, true, 'NONE', 'G2', null, null, 79),
  ('D18-01', 18, 'Handle routine customer queries', 'Handle selected routine customer queries (schedules, documentation).', 'PROCESS', 'ACTIVITY', 'KAM', 18, true, true, 'CUSTOMER', 'G2', null, null, 80),
  ('D18-02', 18, 'Mandatory pre-send review', 'Mentor reviews every outgoing response before it is sent.', 'GOVERNANCE', 'REVIEW', 'MENTOR', 18, true, false, 'NONE', 'G2', null, null, 81),
  ('D19-01', 19, 'Coordinate cross-functional closure', 'Drive closure of open actions across Quality, SCM, Plant and Engineering.', 'PEOPLE', 'ACTIVITY', 'KAM', 19, true, false, 'NONE', 'G2', null, null, 82),
  ('D20-01', 20, 'Lead account-action review', 'Lead one internal review covering quality, delivery, commercial and programme topics.', 'GOVERNANCE', 'ACTIVITY', 'KAM', 20, true, true, 'NONE', 'G2', null, null, 83),
  ('D20-02', 20, 'Mentor observation notes', 'Mentor records observations of the internal review.', 'PEOPLE', 'REVIEW', 'MENTOR', 20, true, false, 'NONE', 'G2', null, null, 84),
  ('D21-01', 21, 'Certification: RFQ response', 'Complete the RFQ-response certification scenario.', 'PROCESS', 'SCENARIO', 'KAM', 21, true, false, 'NONE', 'G2', 'scenario:SCN-RFQ', null, 85),
  ('D21-02', 21, 'Certification: price challenge', 'Complete the price-challenge certification scenario.', 'PROCESS', 'SCENARIO', 'KAM', 21, true, false, 'NONE', 'G2', 'scenario:SCN-PRICE', null, 86),
  ('D21-03', 21, 'Certification: delivery risk', 'Complete the delivery-risk certification scenario.', 'PROCESS', 'SCENARIO', 'KAM', 21, true, false, 'NONE', 'G2', 'scenario:SCN-DELIVERY', null, 87),
  ('D21-04', 21, 'Certification: quality escalation', 'Complete the quality-escalation certification scenario.', 'GOVERNANCE', 'SCENARIO', 'KAM', 21, true, false, 'NONE', 'G2', 'scenario:SCN-QUALITY', null, 88),
  ('D21-05', 21, 'Mentor certification review', 'Mentor reviews certification scenarios and decides the gate.', 'GOVERNANCE', 'REVIEW', 'MENTOR', 21, true, false, 'NONE', 'G2', 'gate:G2', null, 89),
  ('D22-01', 22, 'Prepare commercial position', 'Prepare a commercial position for joint discussion. No autonomous pricing.', 'PROCESS', 'DELIVERABLE', 'KAM', 22, true, true, 'PRICING', 'G3', null, null, 90),
  ('D23-01', 23, 'Reporting Boss reviews position', 'Reporting Boss reviews and challenges the position.', 'GOVERNANCE', 'REVIEW', 'REPORTING_BOSS', 23, true, false, 'PRICING', 'G3', null, null, 91),
  ('D24-01', 24, 'Joint live commercial discussion', 'Join a live commercial discussion jointly with the Reporting Boss.', 'PEOPLE', 'ACTIVITY', 'KAM', 24, true, false, 'PRICING', 'G3', null, null, 92),
  ('D25-01', 25, 'Draft negotiated position', 'Draft the follow-up position for Reporting Boss approval.', 'PROCESS', 'DELIVERABLE', 'KAM', 25, true, true, 'PRICING', 'G3', null, null, 93),
  ('D26-01', 26, 'Own agreed account scope', 'Own the agreed account scope; daily light-touch review.', 'PEOPLE', 'ACTIVITY', 'KAM', 26, true, false, 'CUSTOMER', 'G3', null, null, 94),
  ('D27-01', 27, 'Daily review log', 'Log daily review outcomes with your mentor.', 'PROCESS', 'ACTIVITY', 'KAM', 27, true, false, 'CUSTOMER', 'G3', null, null, 95),
  ('D28-01', 28, 'Alternate-day review log', 'Review cadence moves to alternate days.', 'PROCESS', 'ACTIVITY', 'KAM', 28, true, false, 'CUSTOMER', 'G3', null, null, 96),
  ('D29-01', 29, 'Assemble panel evidence', 'Assemble evidence: live cases, outputs, scenario results, support-event history.', 'GOVERNANCE', 'DELIVERABLE', 'KAM', 29, true, false, 'NONE', 'G3', null, null, 97),
  ('D30-01', 30, 'Mentor panel input', 'Mentor submits panel input.', 'PEOPLE', 'REVIEW', 'MENTOR', 30, true, false, 'NONE', 'G3', 'panel:MENTOR', null, 98),
  ('D30-02', 30, 'HR panel input', 'HR submits panel input.', 'PEOPLE', 'REVIEW', 'HR_ADMIN', 30, true, false, 'NONE', 'G3', 'panel:HR', null, 99),
  ('D30-03', 30, 'Reporting Boss final sign-off', 'Reporting Boss records the final readiness decision.', 'GOVERNANCE', 'REVIEW', 'REPORTING_BOSS', 30, true, false, 'NONE', 'G3', 'panel:SIGNOFF', null, 100)
) as t(code, day_number, title, description, pillar, task_type, owner_role, due_day,
          is_mandatory, requires_approval, exposure, gate_code, action_ref, knowledge_topic, sort_order)
on conflict do nothing;

insert into public.task_dependencies (task_id, depends_on_task_id)
select t.id, d.id
from (values
  ('D05-07', 'D05-01'),
  ('D05-07', 'D05-03'),
  ('D05-07', 'D05-06'),
  ('D07-02', 'D07-01'),
  ('D07-03', 'D07-02'),
  ('D07-04', 'D07-03'),
  ('D07-05', 'D07-04'),
  ('D10-01', 'D07-05'),
  ('D10-02', 'D08-06'),
  ('D10-05', 'D10-01'),
  ('D14-04', 'D11-01'),
  ('D14-04', 'D11-02'),
  ('D14-04', 'D11-03'),
  ('D14-04', 'D12-01'),
  ('D14-04', 'D12-02'),
  ('D14-04', 'D14-01'),
  ('D14-04', 'D14-02'),
  ('D14-04', 'D14-03'),
  ('D15-02', 'D14-04'),
  ('D15-03', 'D14-04'),
  ('D18-02', 'D18-01'),
  ('D20-02', 'D20-01'),
  ('D21-05', 'D21-01'),
  ('D21-05', 'D21-02'),
  ('D21-05', 'D21-03'),
  ('D21-05', 'D21-04'),
  ('D23-01', 'D22-01'),
  ('D24-01', 'D23-01'),
  ('D25-01', 'D24-01'),
  ('D30-03', 'D30-01'),
  ('D30-03', 'D30-02')
) as x(task_code, dep_code)
join public.onboarding_templates tpl on tpl.code = 'KAM-30'
join public.tasks t on t.template_id = tpl.id and t.code = x.task_code
join public.tasks d on d.template_id = tpl.id and d.code = x.dep_code
on conflict do nothing;
